version: '3.8'

services:
  backend:
    build: ./backend
    image: andriikocom/backend:latest
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:metascore@db/invoices
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: andriikocom/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=metascore
      - POSTGRES_DB=invoices
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
