"""empty message

Revision ID: a21dbed7a440
Revises: a4b0f089dc96
Create Date: 2024-07-16 19:48:26.182136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21dbed7a440'
down_revision = 'a4b0f089dc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incominginvoice', schema=None) as batch_op:
        batch_op.drop_column('total_vat')
        batch_op.drop_column('total_amount')

    with op.batch_alter_table('outgoinginvoice', schema=None) as batch_op:
        batch_op.drop_column('total_vat')
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outgoinginvoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_vat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    with op.batch_alter_table('incominginvoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_vat', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
