"""empty message

Revision ID: 60e8e4ed69a2
Revises: 3487a42bec82
Create Date: 2024-07-22 16:49:46.262758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e8e4ed69a2'
down_revision = '3487a42bec82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outgoinginvoiceitem', schema=None) as batch_op:
        batch_op.drop_constraint('outgoinginvoiceitem_outgoing_invoice_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'outgoinginvoice', ['outgoing_invoice_id'], ['outgoing_invoice_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outgoinginvoiceitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('outgoinginvoiceitem_outgoing_invoice_id_fkey', 'outgoinginvoice', ['outgoing_invoice_id'], ['outgoing_invoice_id'])

    # ### end Alembic commands ###
