"""empty message

Revision ID: a779c0d0dba6
Revises: 7e6d420d5f22
Create Date: 2024-07-20 00:57:44.336944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a779c0d0dba6'
down_revision = '7e6d420d5f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incominginvoiceitem', schema=None) as batch_op:
        batch_op.drop_constraint('incominginvoiceitem_incoming_invoice_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'incominginvoice', ['incoming_invoice_id'], ['incoming_invoice_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incominginvoiceitem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('incominginvoiceitem_incoming_invoice_id_fkey', 'incominginvoice', ['incoming_invoice_id'], ['incoming_invoice_id'])

    # ### end Alembic commands ###
